### ISSUE TITLE
Login - Display Errors when Login Fails

### ISSUE THREAD

**Issue by cahuizar** [CS450-ECE461/fall2016-group1-userportal#17]
When performing certain actions, the app continuously attempts loading instead of displaying an error message. For example, when registering for an account, if a username/email has already been used, an error should be displayed instead of just not loading the next screen. This problem also persists for incorrect passwords, logging into accounts that don't exist, and others.

This problem needs to be addressed by taking the error messages given from the back end API and displaying information on the front end to alert the user to the issue.

**Comment by jsatterw** [comment]
A pull request for the branch display_login_errors has been made. This branch includes code that displays errors for the standard login issues of incorrect username and/or password. Once the pull request is merged, this issue can be closed.
